os:
  - linux

before_install:
  - sudo apt-get -qq install lib32stdc++6

install:
  - wget http://isabelle.in.tum.de/dist/Isabelle2017_app.tar.gz
  - tar -xzvf Isabelle2017_app.tar.gz

cache:
  directories:
    - $HOME/.isabelle

script:
  travis_wait 120 Isabelle2017/bin/isabelle build -v -D .
