(* ARM_Monadic.thy - generated by L3 - 25/04/2017 *)
theory ARM_Monadic_updated
imports "$ISABELLE_HOME/src/HOL/Word/Word"  TLB
begin

ML_file "$ISABELLE_HOME/src/HOL/Word/Tools/word_lib.ML"
ML_file "./../L3_Lib/L3.ML"



datatype exception =
    ASSERT string
  | AlignmentFault "32 word"
  | IMPLEMENTATION_DEFINED string
  | NoException
  | UNPREDICTABLE string
  | VFP_EXCEPTION string
  | PAGE_FAULT string (* MMU *)



record state =
  MEM :: "paddr \<rightharpoonup> byte"
  exception :: exception
  TTBR0 :: paddr 
  ASID :: asid


class mmu =
  fixes mmu_translate :: "vaddr \<Rightarrow> 'a state_scheme \<Rightarrow> paddr \<times> 'a state_scheme" 

class mem_op = mmu +
  fixes mmu_read :: "vaddr \<Rightarrow> 'a state_scheme \<Rightarrow> bool list \<times> 'a state_scheme"
  fixes mmu_read_size :: "vaddr \<times> nat  \<Rightarrow> 'a state_scheme \<Rightarrow> bool list \<times> 'a state_scheme"
  fixes mmu_write_size :: "bool list \<times> vaddr \<times> nat \<Rightarrow> 'a state_scheme \<Rightarrow> unit \<times> 'a state_scheme"

class  reg_tlb_op =
  fixes update_TTBR0 :: "paddr \<Rightarrow> 'a state_scheme \<Rightarrow>  unit \<times> 'a state_scheme" 
  fixes update_ASID :: "asid \<Rightarrow> 'a state_scheme \<Rightarrow>  unit \<times> 'a state_scheme" 
  fixes Flush_TLB :: "'a state_scheme \<Rightarrow>  unit \<times> 'a state_scheme" 
  fixes Flush_ASID :: "asid \<Rightarrow> 'a state_scheme \<Rightarrow>  unit \<times> 'a state_scheme" 
  fixes Flush_varange :: "vaddr set \<Rightarrow> 'a state_scheme \<Rightarrow>  unit \<times> 'a state_scheme" 
  fixes Flush_ASIDvarange :: "asid \<Rightarrow> vaddr set \<Rightarrow> 'a state_scheme \<Rightarrow>  unit \<times> 'a state_scheme" 



end